Add linter to docs
apify/apify-docs pull request #112
Opened 2020-10-15 14:19 UTC by m-murasovs

Adding [markdownlint](https://github.com/DavidAnson/markdownlint) to apify-docs. 

With the VSCode [extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint), we can set it to fix all the violations on Save.

I also want to add it to the build script, so that the violations would be highlighted (or, if the violation is serious, we could have a proper error)

Currently linting for: 
- link formatting
- headings

2020-10-19 11:53 UTC, mtrunkat commented
One minor thing - I'd separate lint and test flows in Github actions from the build and deploy. That way you will see which flows are passing and which not as you can see here in the main repo: https://cln.sh/O44meU

So you would see here:
- Code lint pass
- Markdown lint failed
- Deploy skipped (because lint failed)

2020-10-19 11:53 UTC, mtrunkat approved these changes

2020-10-21 07:29 UTC, fnesveda commented
@m-murasovs The markdownlint check still fails with a bunch of issues, could you fix those as well?

2020-10-21 08:10 UTC, m-murasovs commented
@fnesveda sorry, forgot to write - those are from the proxy docs and will be fixed when proxy docs get merged (currently there's no point fixing them). 

I've turned this into a draft until proxy docs get merged.

2020-10-26 13:38 UTC, m-murasovs commented
Currently looking for a way to allow the 'await' keyword outside async functions, however ESLint doesn't have rules for this.

2020-10-27 17:57 UTC, fnesveda requested changes
There's a lot of instances where there's a code block containing just an URL or just one line of text, but the code language is set as `json`. I'd use `text` there, it's gonna be less confusing when rendered in the code tabs.

2020-10-27 17:57 UTC, fnesveda commented on docs/webhooks/events.md
> +`ACTOR.RUN.CREATED` - new actor run has been created.
You've probably deleted the `*` here accidentally

2020-10-27 17:57 UTC, fnesveda commented on docs/proxy/datacenter_proxy.md
> +<<<<<<< HEAD
You missed a merge conflict here.

2020-10-27 18:16 UTC, fnesveda requested changes

2020-10-27 18:16 UTC, fnesveda commented on docs/actors/development/source_code.md
> +```text
This could actually be `dockerfile` instead of `text`

2020-10-27 18:23 UTC, fnesveda approved these changes

2020-10-28 12:00 UTC, fnesveda approved these changes

2020-11-01 14:06 UTC, mtrunkat approved these changes
Looks good!

2020-11-02 09:13 UTC, merged