feat(academy): add advanced crawling section with sitemaps and search
apify/apify-docs pull request #1217
Opened 2024-09-16 22:19 UTC by metalwarrior665

2024-09-17 12:54 UTC, metalwarrior665 commented
Will process the lint issues

2024-09-18 10:40 UTC, metalwarrior665 commented
@TC-MO If we change URL of an article, do I need to contact web team to set a hard redirect?

2024-09-18 11:09 UTC, TC-MO commented
I think we do redirects in nginx.conf file not sure if there is any other way

2024-09-18 11:12 UTC, metalwarrior665 commented
TODO redirect 
..._web_scraping/scraping_paginated_sites.md → ...scraping/crawling/crawling-with-search.md

2024-09-19 12:46 UTC, TC-MO requested changes

2024-09-19 12:46 UTC, TC-MO commented on sources/academy/tutorials/node_js/scraping_from_sitemaps.md
> +>Crawlee recently introduced a new feature that allows you to scrape sitemaps with ease. If you are using Crawlee, you can skip the following steps and just gather all the URLs from the sitemap in a
This feels like unnecesary dating ? When is "recently" ? Also I think this could work better as admonitions instead of blockquote.

2024-09-19 12:46 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +menuWeight: 2
Is this something that is custom created by Apify? I haven't seen this anywhere else

2024-09-19 12:46 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +paths:
isn't this supposed to be `slug:` ?

2024-09-19 12:46 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +## [](#how-to-set-up-http-requests-to-download-sitemaps) How to set up HTTP requests to download sitemaps
if anchors do not differ from headings then these are unnecessary from what I remember

2024-09-19 12:46 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +```javascript
could we switch it to ```js? Sometime back we changed this for consistency across Academy & Platform docs. I'll add this info to contributing guidelines.

2024-10-07 11:27 UTC, honzajavorek commented
Will review, but I think I will wait for @TC-MO's comments to be addressed first.

2025-02-01 11:41 UTC, metalwarrior665 commented on sources/academy/tutorials/node_js/scraping_from_sitemaps.md
> +>Crawlee recently introduced a new feature that allows you to scrape sitemaps with ease. If you are using Crawlee, you can skip the following steps and just gather all the URLs from the sitemap in a
Good point, I also added `:::note` but not sure how much better it looks. I don't like it is not native markdown so I don't see preview

2025-02-01 11:42 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +menuWeight: 2
I think I probably dig the old code from some system before it was refactored. I changed to `sidebar_position`

2025-02-01 11:42 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +paths:
Changed too

2025-02-01 11:42 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +## [](#how-to-set-up-http-requests-to-download-sitemaps) How to set up HTTP requests to download sitemaps
Changed too

2025-02-01 11:43 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +```javascript
changed

2025-02-01 11:43 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +The core crawling problem comes to down to ensuring that we reliably find all detail pages on the target website or inside its categories. This is trivial for small sites. We just open the home page
Google says `home page` is valid. don't want to block the PR on this now :)

2025-02-01 11:44 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/index.md
>  # Advanced web scraping
I'm not sure why I would remove the h1 since it will look different in pure markdown and it doesn't cause any issue. Or do you mean to remove the whole text?

2025-02-01 11:44 UTC, metalwarrior665 commented on sources/academy/webscraping/advanced_web_scraping/index.md
> +## [](#what-does-production-ready-mean) What does production-ready mean?
Fixed

2025-02-01 11:45 UTC, metalwarrior665 commented
@TC-MO I addressed the remarks and rebased to master, pls take a look. I will see the tests

2025-02-03 14:38 UTC, honzajavorek requested changes
🔴 I think the front matter contains double semicolons, which could be a syntax error or a silent error causing unexpected problems.

🟠 I made a few suggestions on improvements. My aim was to add to readability and flow of the sentences. I steered the text towards being language-agnostic, but I didn't check the whole context of the course to see if it's necessary or not. I suggested to remove certain emotional phrases, such as "fortunately". Saying "next" together with "lessons" didn't feel right, so I suggest using "following lessons" and to keep "next" for just one lesson. You mention framework several times, and while it's perfectly valid, my idea would be to keep that word only for Crawlee (or Scrapy and others), and find other words to call the rest, such as algorithm, tool, or approach. I think separating those two clearly will remove some amount of possible confusion. When linking to content, I prefer to put actual text and names to the link text instead of "see this article", and I think it's also a web document accessibility rule.

⚪️ I could imagine a bit more polishing of the flow of the sentences, and sometimes they could be more brief, but I don't think that's something we should do in PR reviews, it's highly subjective and a lot of back and forth. For minimalistic Czenglish check I can highly recommend "Is this correct English?" prompt to ChatGPT, followed by a Markdown block of whatever you want to check. It keeps your writing as is, but provides basic grammar and flow fixes. The text then sounds like you, but is more smooth. I use it a lot.

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
> +Fortunately, you don't have to worry about any of the above steps if you use [Crawlee](https://crawlee.dev) which has rich traversing and parsing support for sitemap. Crawlee can traverse nested site
```suggestion
Fortunately, you don't have to worry about any of the above steps if you use [Crawlee](https://crawlee.dev), a scraping framework, which has rich traversing and parsing support for sitemap. It can traverse nested sitemaps, download, and parse compressed sitemaps, and extract URLs from them. You can get all the URLs in a few lines of code:
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/crawling-with-search.md
> +sidebar_position:: 3
```suggestion
sidebar_position: 3
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +sidebar_position:: 1
```suggestion
sidebar_position: 1
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +The core crawling problem comes to down to ensuring that we reliably find all detail pages on the target website or inside its categories. This is trivial for small sites. We just open the home page
Web Scraping for Beginners course - link?

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +Unfortunately, **most modern websites restrict pagination** only to somewhere between 1 and 10 000 products. Solving this problem might seem relatively straightforward at first but there are multiple
```suggestion
Unfortunately, **most modern websites restrict pagination** only to somewhere between 1 and 10,000 products. Solving this problem might seem relatively straightforward at first but there are multiple hurdles that we will explore in this lesson.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Streamed, compressed, and archived** - Sitemaps are often streamed and archived with .tgz extensions and compressed with gzip. This means that you cannot use default HTTP client settings and must
```suggestion
- **Streamed, compressed, and archived** - Sitemaps are often streamed and archived with .tgz extensions and compressed with gzip. This means that you cannot use default HTTP client settings and must handle these cases with extra code or use a scraping framework.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +This approach means traversing the website like a normal user do by going through categories, setting up different filters, ranges and sorting options. The goal is to traverse it is a way that ensure
```suggestion
This approach means traversing the website like a normal user does by going through categories, setting up different filters, ranges, and sorting options. The goal is to ensure that we cover all categories or ranges where products can be located, and that for each of those we stay under the pagination limit.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +The pros and cons of this approach are pretty much the opposite of the sitemaps approach.
```suggestion
The pros and cons of this approach are pretty much the opposite of relying on sitemaps.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Complex to set up** - The logic to traverse the website is usually more complex and can take a lot of time to get right. We will get to this in the next lessons.
```suggestion
- **Complex to set up** - The logic to traverse the website is usually complex and can take a lot of time to get right. We will get to this in the next lessons.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Not always complete** - Sometimes the combination of filters and categories will not allow us to ensure we have all products. This is especially painful for sites where we don't know the exact nu
```suggestion
- **Not always complete** - Sometimes the combination of filters and categories will not allow us to ensure we have all products. This is especially painful for sites where we don't know the exact number of products we are looking for. The tools we'll build in the following lessons will help us with this.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +Fortunately, most websites list a total number of detail pages somewhere. It might be displayed on the home page or search results or be provided in the API response. We just need to make sure that t
```suggestion
Most websites list a total number of detail pages somewhere. It might be displayed on the home page, search results, or be provided in the API response. We just need to make sure that this number really represents the whole site or category we are looking to scrape. By knowing the total number of products, we can tell if our approach to scrape all succeeded or if we still need to refine it.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +Unfortunately, some sites like Amazon do not provide exact numbers. In this case, we have to work with what they give us and put even more effort into making our scraping logic accurate. We will tack
```suggestion
Some sites, like Amazon, do not provide exact numbers. In this case, we have to work with what they give us and put even more effort into making our scraping logic accurate. We will tackle this in the following lessons as well.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +First, we will look into the easier approach, the [sitemap crawling](./crawling-sitemaps.md). Then we will go through all the intricacies of the category, search and filter crawling, and build up a g
```suggestion
Next, we will look into [sitemap crawling](./crawling-sitemaps.md). After that we will go through all the intricacies of the category, search and filter crawling, and build up tools implementing a generic approach that we can use on any website. At last, we will combine the results of both and set up monitoring and persistence to ensure we can run this regularly without any manual controls.
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/index.md
> +sidebar_position:: 6
```suggestion
sidebar_position: 6
```

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/advanced_web_scraping/index.md
> +<!--
WIP?

2025-02-03 14:38 UTC, honzajavorek commented on sources/academy/webscraping/api_scraping/general_api_scraping/handling_pagination.md
> +Sometimes, APIs have limited pagination. That means that they limit the total number of results that can appear for a set of pages, or that they limit the pages to a certain number. To learn how to h
```suggestion
Sometimes, APIs have limited pagination. That means that they limit the total number of results that can appear for a set of pages, or that they limit the pages to a certain number. To learn how to handle these cases, take a look at the [Crawling with search](/academy/advanced-web-scraping/crawling/crawling-with-search) article.
```

2025-02-05 11:07 UTC, TC-MO requested changes

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +Both of these approaches have their pros and cons so the best solution is to **use both and combine the results**. Here we will learn why.
```suggestion
Both of these approaches have their pros and cons so the best solution is to _use both and combine the results_. Here we will learn why.
```

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Usually complete** - Websites have an incentive to keep their sitemaps up to date as they are used by search engines. This means that they usually contain all pages on the website.
```suggestion
- _Quick to set up_ - The logic to find all sitemaps and extract all URLs is usually simple and can be done in a few lines of code.
- _Fast to run_ - You only need to run a single request for each sitemap that contains up to 50,000 URLs. This means you can get all the URLs in a matter of seconds.
- _Usually complete_ - Websites have an incentive to keep their sitemaps up to date as they are used by search engines. This means that they usually contain all pages on the website.
```

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Streamed, compressed, and archived** - Sitemaps are often streamed and archived with .tgz extensions and compressed with gzip. This means that you cannot use default HTTP client settings and must
```suggestion
- _Does not directly reflect the website_ - There is no way you can ensure that all pages on the website are in the sitemap. The sitemap also can contain pages that were already removed and will return 404s. This is a major downside of sitemaps which prevents us from using them as the only source of URLs.
- _Updated in intervals_ - Sitemaps are usually not updated in real-time. This means that you might miss some pages if you scrape them too soon after they were added to the website. Common update intervals are 1 day or 1 week.
- _Hard to find or unavailable_ - Sitemaps are not always trivial to locate. They can be deployed on a CDN with unpredictable URLs. Sometimes they are not available at all.
- _Streamed, compressed, and archived_ - Sitemaps are often streamed and archived with .tgz extensions and compressed with gzip. This means that you cannot use default HTTP client settings and must handle these cases with extra code or use a scraping framework.
```

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Often contain detailed data** - While sitemaps are usually just a list of URLs, categories, searches and filters often contain additional data like product names, prices, categories, etc, especia
```suggestion
- _Directly reflects the website_ - With most scraping use-cases, we want to analyze the website as the regular users see it. By going through the intended user flow, we ensure that we are getting the same pages as the users.
- _Updated in real-time_ - The website is updated in real-time so we can be sure that we are getting all pages.
- _Often contain detailed data_ - While sitemaps are usually just a list of URLs, categories, searches and filters often contain additional data like product names, prices, categories, etc, especially if available via JSON API. This means that we can sometimes get all the data we need without going to the detail pages.
```

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
> +- **Not always complete** - Sometimes the combination of filters and categories will not allow us to ensure we have all products. This is especially painful for sites where we don't know the exact nu
```suggestion
- _Complex to set up_ - The logic to traverse the website is usually complex and can take a lot of time to get right. We will get to this in the next lessons.
- _Slow to run_ - The traversing can require a lot of requests. Some filters or categories will have products we already found.
- _Not always complete_ - Sometimes the combination of filters and categories will not allow us to ensure we have all products. This is especially painful for sites where we don't know the exact number of products we are looking for. The tools we'll build in the following lessons will help us with this.
```

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/advanced_web_scraping/index.md
> +In [**Web scraping for beginners**](/academy/web-scraping-for-beginners) course, we have learned the necessary basics required to create a scraper. In the following courses, we learned more about spe
```suggestion
In [Web scraping for beginners](/academy/web-scraping-for-beginners) course, we have learned the necessary basics required to create a scraper. In the following courses, we learned more about specific practices and techniques that will help us to solve most of the problems we will face.
```

2025-02-05 11:07 UTC, TC-MO commented on sources/academy/webscraping/api_scraping/general_api_scraping/handling_pagination.md
>  ## Final note {#final-note}
```suggestion
## Final note
```

2025-02-05 13:22 UTC, TC-MO approved these changes
LGTM

2025-02-17 22:34 UTC, honzajavorek reviewed
I made a very quick glance over the changes and they look okay. I don't have time for a full re-review right now, so feel free to go with Michał's approval.

2025-02-18 09:09 UTC, merged