docs: add information regarding session and organization security settings
apify/apify-docs pull request #1223
Opened 2024-09-23 09:11 UTC by DaveHanns

2024-09-23 09:16 UTC, gippy approved these changes

2024-09-23 12:55 UTC, TC-MO requested changes

2024-09-23 12:55 UTC, TC-MO commented on sources/platform/collaboration/organization_account/setup.md
> +In the **Account** tab's **Security** section, you can impose security requirements on organization members, such as their maximum session lifespan or whether they are required to turn on two-factor
```suggestion
After creating your organization, you can configure its settings. The **Account** tab, allows you to: 

- Set the organization's email address
- Change the username
- Configure security settings
- Delete the account.

The **Members** tab e;ts you to update your organization's members and set its owner.

In the **Account** tab's **Security** section, you can set security requirements for organization members. These include:

- Maximum session lifespan
- Two-factor authentication requirement
```

2024-09-23 12:55 UTC, TC-MO commented on sources/platform/console/settings.md
> +
```suggestion
### Session Information

In the **Session Information** section, you can adjust the session configuration. You can modify the default session lifespan of 90 days, this customization helps ensure compliance with organization security policies.

```

2024-09-23 12:55 UTC, TC-MO commented on sources/platform/console/two-factor-authentication.md
> +
```suggestion
Some organizations might require two-factor authentication (2FA) to access their resources.  Members of such an organization, must enable 2FA on their account in order to continue accessing shared resources and maintain compliance with their security policies.

```

2024-09-24 08:04 UTC, TC-MO approved these changes
LGTM

2024-09-24 08:26 UTC, merged