feat: add initial PPE documentation
apify/apify-docs pull request #1256
Opened 2024-10-16 14:57 UTC by mhamas

This PR is adding initial documentation for pay-per-event Actor pricing model. The product is very young. As it evolves, we will keep updating the documentation.

This is end-user facing documentation. We will write separate documentation for creators once the pricing model becomes available to external developers.

2024-10-17 12:21 UTC, TC-MO requested changes
few suggestions

2024-10-17 12:21 UTC, TC-MO commented on sources/platform/actors/running/store.md
> +![Pay per event actor - historical usage tab](./images/store/pay_per_event_historical_usage_tab.png)
```suggestion
![Pay per event Actor - historical usage tab](./images/store/pay_per_event_historical_usage_tab.png)
```

2024-10-17 12:21 UTC, TC-MO commented on sources/platform/actors/running/store.md
> +![Pay per event actor - run detail](./images/store/pay_per_event_price_on_run_detail.png)
```suggestion
![Pay per event Actor - run detail](./images/store/pay_per_event_price_on_run_detail.png)
```

2024-10-17 12:21 UTC, TC-MO commented on sources/platform/actors/running/store.md
> +![Pay per event actor - max charge per run](./images/store/pay_per_event_price_on_run_detail.png)
```suggestion
![Pay per event Actor - max charge per run](./images/store/pay_per_event_price_on_run_detail.png)
```

2024-10-17 12:21 UTC, TC-MO commented on sources/platform/actors/running/store.md
> +3. [**Pay per event**](#pay-per-event) - you do not pay for platform usage the Actor generates and instead just pay for the specific events the Actor creator defines, such as for generating a single
```suggestion
3. [**Pay per event**](#pay-per-event) - you can run the Actor and you do not pay for platform usage the Actor generates. Instead you pay for the specific events the Actor creator defines, such as for generating a single result or starting the Actor.
```

2024-10-21 08:57 UTC, mhamas commented
@TC-MO I applied suggestions. Can you please take another look? Thx

2024-10-21 09:01 UTC, TC-MO approved these changes
Just one comment to fix the markdownlint issues otherwise looks good

2024-10-21 09:01 UTC, TC-MO commented on sources/platform/actors/running/store.md
> +#### Pay per event Actors - Frequently Asked Questions
add blank line after headings that will fix the markdownlint issues

2024-10-21 09:09 UTC, merged