docs: add resourceType property to support storage picker
apify/apify-docs pull request #1261
Opened 2024-10-22 17:58 UTC by MFori

Proposal of new input schema property `resourceType` (based on https://apify.slack.com/archives/C01VBUV81UZ/p1729081102142439?thread_ts=1728031818.871689&cid=C01VBUV81UZ) which will solve the needs of storages picker (https://github.com/apify/apify-core/issues/12871)

As I already verified, in ajv schema there would be two new top level properties `resourceProperty` and `resourceArrayProperty`, ajv can distinguish between these and `stringProperty` with `arrayProperty` based on the required `resourceType` property. The `editor` property is optional with default value of `resourcePicker`.
Input schema PR will come when this one is approved.

The description is tightly connected with storages even though later the `resourceType` should support other types of resources, but for now I think it's ok like this.

Preview of docs:

<img width="817" alt="Screenshot 2024-10-22 at 19 47 38" src="https://github.com/user-attachments/assets/26b2a4f9-332c-448c-aacc-9150d07e6ce6">
<img width="806" alt="Screenshot 2024-10-22 at 19 47 51" src="https://github.com/user-attachments/assets/5517a1fa-6286-49f6-a571-25a175e7dad4">

2024-10-23 07:55 UTC, jancurn commented on sources/platform/actors/development/actor_definition/input_schema/specification.md
> +### Resource
Why not "Resource type" ?

2024-10-23 07:58 UTC, jancurn commented on sources/platform/actors/development/actor_definition/input_schema/specification.md
> +The Resource property enables Actor users to select different types of resources.
I'd say that:

Resource type identifies what kind of object is referred to in the input field. For example, a the Key-value store resource type can be referred to using a string ID.

2024-10-23 09:42 UTC, mtrunkat requested changes
I am missing info what is the returned value in a case of an array vs string. There is screenshot only for string. I'd also improve the wording there mentioning that the return value is the resource ID itself.

Otherwise good to go after the other comments are fixed.

2024-10-23 10:07 UTC, MFori commented
> I am missing info what is the returned value in a case of an array vs string. There is screenshot only for string. I'd also improve the wording there mentioning that the return value is the resource ID itself.
> 
> Otherwise good to go after the other comments are fixed.

I update it based on @jancurn comments and try to better mention that the return value is the resource ID:
I can also include screenshot for array input once we have it implemented.

![Screenshot 2024-10-23 at 12 05 23](https://github.com/user-attachments/assets/a229b58f-9fec-46f7-9ea9-b73d3e93bbb1)

2024-10-23 18:00 UTC, gippy approved these changes
Just one question. Since these docs already mention, that we support arrays too. Are you planning to update the resource picker in UI to support arrays?

If not then we should not mention arrays until we actually decide that we want to implement them.

2024-10-23 18:58 UTC, MFori commented
> Just one question. Since these docs already mention, that we support arrays too. Are you planning to update the resource picker in UI to support arrays?
> 
> If not then we should not mention arrays until we actually decide that we want to implement them.

Yeah I have almost done it in UI too

2024-10-24 05:56 UTC, jancurn commented
I assume we don't allowed both string and array at the same time, that the input type can be just one of them. Right?

2024-10-24 06:19 UTC, MFori commented
> I assume we don't allowed both string and array at the same time, that the input type can be just one of them. Right?

Exactly, there is still the `type` property with value of `string` or `array`:

<img width="809" alt="Screenshot 2024-10-24 at 8 17 34" src="https://github.com/user-attachments/assets/02de1f9f-1d43-4893-b3a3-c39d474ce987">

2024-10-24 09:20 UTC, mtrunkat approved these changes

2024-10-24 09:55 UTC, netmilk approved these changes
It looks all ok to me! 

One small thing to consider: adding context to the terms "object" and "resource" where possible makes it easier to understand they are related to Apify's architecture and not just a "resource" or "object" from the generic programming or integration/API domain language.

2024-10-24 09:55 UTC, netmilk commented on sources/platform/actors/development/actor_definition/input_schema/specification.md
> +Resource type identifies what kind of object is referred to in the input field. For example, the Key-value store resource type can be referred to using a string ID.
```suggestion
Resource type identifies what kind of Apify Platfrom object is referred to in the input field. For example, the Key-value store resource type can be referred to using a string ID.
```

2024-10-24 09:55 UTC, netmilk commented on sources/platform/actors/development/actor_definition/input_schema/specification.md
> +| `resourceType` | One of <ul><li>`dataset`</li><li>`keyValueStore`</li><li>`requestQueue`</li></ul> | Yes      | Type of resource                                                                   |
```suggestion
| `resourceType` | One of <ul><li>`dataset`</li><li>`keyValueStore`</li><li>`requestQueue`</li></ul> | Yes      | Type of Apify Platform resource                                                                   |
```

2024-11-14 19:16 UTC, merged