fix(request-queue): Update request qeue locking docs
apify/apify-docs pull request #1322
Opened 2024-12-06 13:12 UTC by drobnikj

I made some changes regarding the API changes.

2024-12-09 10:04 UTC, fnesveda requested changes
Looks good, but the variable naming is a bit confusing, could you improve it?

2024-12-09 10:04 UTC, fnesveda commented on sources/platform/storage/request_queue.md
> +const requestLockedByClientOne = await requestQueueClientOne.getRequest(
The naming of these two variables is pretty confusing, I don't really know what's the difference between `theFirstRequestLockedByClientOne` and `requestLockedByClientOne`, especially by name. Could you come up with some better names?

2024-12-09 10:04 UTC, fnesveda commented on sources/platform/storage/request_queue.md
> +const wasTheClientTwoLockedSameRequest = !!processingRequestsClientTwo.items.find(
Here I'm also not sure what the varaible means, could you rename it, or explain better in the comment?

2024-12-09 10:58 UTC, fnesveda approved these changes

2024-12-10 09:27 UTC, TC-MO requested changes

2024-12-10 09:37 UTC, TC-MO approved these changes

2024-12-10 09:41 UTC, merged