Api reference: Deprecated disableRedirect param and direct-upload kvs endpoint
apify/apify-docs pull request #194
Opened 2021-02-24 11:12 UTC by drobnikj

It is not aligned with the current state of API regarding the decompression of record. We decompress just records requested with disableRedirect param. We plan to do it, I will merge this after.

2021-02-25 08:08 UTC, m-murasovs approved these changes
Looks good, just minor grammar stuff :)

2021-02-25 08:08 UTC, m-murasovs commented on docs/api_v2/api_v2_reference.apib
> +The most HTTP client supports decompression by default. After using the HTTP client with decompression support, the `Accept-Encoding` header is set by the client and body is decompressed automaticall
Here, do you mean "Most HTTP clients support... "?

2021-02-25 08:08 UTC, m-murasovs commented on docs/api_v2/api_v2_reference.apib
> +There is a list of supported `Content-Encoding` types.
Please change to "Below is a list..."

2021-02-26 08:48 UTC, mtrunkat approved these changes

2021-03-03 08:17 UTC, m-murasovs requested changes
Sorry, approved before by accident - a couple minor things :D

2021-03-09 08:20 UTC, m-murasovs approved these changes

2021-03-09 13:56 UTC, merged