Docs: Add note about inconsistency of itemCount in dataset info
apify/apify-docs pull request #248
Opened 2021-06-08 14:23 UTC by drobnikj

2021-06-09 07:07 UTC, mtrunkat approved these changes

2021-06-09 07:30 UTC, m-murasovs requested changes

2021-06-09 07:30 UTC, m-murasovs commented on docs/api_v2/api_v2_reference.apib
> +There is a short period(up to 5 seconds) during which these counters may not match with exact counts in dataset items.
`data were pushed` => `data are pushed`

Please add a space in `period(up to 5 seconds)` => `period (up to 5 seconds)`

Thanks!

2021-06-21 11:59 UTC, m-murasovs approved these changes

2021-06-21 12:00 UTC, merged