Web scraping academy first draft
apify/apify-docs pull request #299
Opened 2021-11-22 19:47 UTC by mnmkng

As agreed with @mtrunkat I'm adding the first several chapters of the Web Scraping Academy to the current docs. Once we have the `/developers` portal, we will move this part out again, to a separate instance of the "docs platform".

2021-11-29 13:49 UTC, m-murasovs requested changes
As always, excellent work! Kinda forgot that I was meant to be proof-reading and just ended up learning 😄 Also the shorter articles are a great touch - easy to navigate and not overwhelming.

I did some pedant-level edits but nothing major/structural comes to mind.

Some notes for the future:
- let's use the Oxford comma in lists: e.g. 1, 2**,** and/or 3 instead of 1, 2 and/or 3
- to highlight non-code like tab names or some text example, please make it bold and just use code highlighting for code bits
- For SEO gainz, meta descriptions should be between 120 and 150/160 characters (details vary according to source), so if you can boost those where needed, that would be cool
- It's nice to be more CTA (call to action) with links, with the link early in the sentence. So instead of "for more info, click [here](...)", it's nicer have the link at the front in CTA format: "[Learn more about functions] if you don't know functions."
- There are some varied instances of singular and plural 'data'. I don't really have a preference but it would be good to have the same one
- Emojis work quite well for me in this - maybe more emojis?

2021-11-29 14:57 UTC, mnmkng commented on docs/data_collection_fundamentals/using_devtools.md
> +If you were able to get the same result in your browser console, congratulations! You successfully collected your first data. If not, don't worry and review your code carefully. You'll crush the bug
Is this good or bad? 😄

2021-11-29 14:57 UTC, mnmkng commented on docs/academy.md
> +  * Anti*scraping protection
Yup, will fix.

2021-11-29 14:59 UTC, mnmkng commented on docs/academy.md
> +The course begins with short theory and continues with practical examples of collecting the most popular websites on the internet using your browser console. So let's get to it!
I was hoping the user would use the "next link" in the docs. But then I found that it's not very prominent (I thought it was a big button) and it's also under the feedback thumbs. So I'm not sure what to do now 😄

2021-11-29 14:59 UTC, mnmkng commented on docs/data_collection_fundamentals/using_devtools.md
> +> Websites change and the structure or the HTML or the CSS selectors can become outdated. We'll try our best to keep this tutorial updated, but if you find that what you see on the website does not m
I don't have high hopes for this, but I can try at least 😄

2021-11-29 15:00 UTC, mnmkng commented on docs/data_collection_fundamentals/devtools_continued.md
> +And that's it. With a bit of trial and error you will be able to collect any data from a webpage that's loaded in your browser. This is a useful skill on its own. It will save you time when you need
Yeah, good catch. Will change.

2021-11-29 15:14 UTC, m-murasovs commented on docs/data_collection_fundamentals/using_devtools.md
> +If you were able to get the same result in your browser console, congratulations! You successfully collected your first data. If not, don't worry and review your code carefully. You'll crush the bug
The best!

2021-11-29 15:16 UTC, m-murasovs commented on docs/academy.md
> +The course begins with short theory and continues with practical examples of collecting the most popular websites on the internet using your browser console. So let's get to it!
Damn, I maintain the docs and I constantly forget the "next link" is there 😄 I'd say please link in the paragraph, just so it's obviously there for people

2021-11-30 14:44 UTC, mnmkng commented
closing in favor of #307

2021-11-30 14:44 UTC, closed without merging