Revise the repo structure and build scripts to accommodate other subdomains
apify/apify-docs pull request #321
Opened 2022-02-11 10:48 UTC by m-murasovs

- restructuring the content so it would live in the below repos
- 	`/content/docs`
-  `/content/academy`

This way, we can add future folders there and not clutter the root of the dir.

- Updated the build script to automatically find all the folders in `/content` and create builds for them in `/build` (so we don't need to keep manually adding folders and duplicating code)
- Updated the webp converter script to be automatic as well
- Slight update to the README but I expect we'll need to add more stuff about the academy
- Tried to document the code better because it took me ages to understand what each function does. Please add suggestions how we can make it clearer

**Important**
I don't think we need to update the S3 and Branch scripts, but please have a look - I'm not too sure about how this works.

resolves apify/apify-web#1574

2022-02-14 12:05 UTC, mtrunkat requested changes

2022-02-14 12:05 UTC, mtrunkat commented on src/webp_converter.js
> +                await convertImagesToWebp(dir);
Oh no, @m-murasovs, promises won't work this way! With map/forEach you would have to use the async package. I'd go with `for (... of`

2022-02-15 08:23 UTC, mtrunkat approved these changes
Should be fine but we need to be careful with merge not to break our docs!

2022-02-17 13:15 UTC, Strajk approved these changes
The scripts folder seems little bit complicated for my taste, but it looks like it works correctly 👍

2022-02-23 09:35 UTC, merged