Update deploying section
apify/apify-docs pull request #368
Opened 2022-05-18 10:15 UTC by mstephen19

2022-05-18 11:29 UTC, mstephen19 commented
View preview [here](https://developers.apify.com/academy/apify-platform/deploying-your-code?version=update-deploying#our-example-project)

2022-05-18 12:02 UTC, mnmkng requested changes

2022-05-18 12:02 UTC, mnmkng commented on content/academy/apify_platform/deploying_your_code.md
> +![Supported languages]({{@asset apify_platform/images/supported-languages.webp}})
Can we make this image smaller? It's a bit overwhelming.

2022-05-18 22:08 UTC, mstephen19 commented
Image size is now 70% of what it originally was.

2022-05-19 07:50 UTC, mnmkng commented
> Image size is now 70% of what it originally was.
It's still the same. Full screen.
<img width="1076" alt="CleanShot 2022-05-19 at 09 49 44@2x" src="https://user-images.githubusercontent.com/23726914/169241319-a297e81f-6f7c-4d72-9c1e-15b9e8701c19.png">

2022-05-19 08:25 UTC, mstephen19 commented
> I understand what you meant by size. The KB of the image. Well, that's also important. I notice the deployment image is pretty huge and the languages are not small either.
> 
> The way to do this is to reduce the PNG resolution first - this will not only reduce it's KBs, but also it's size on the page. Then you can try to make it even smaller in KBs with tinypng and if that does not work, then there's the WEBP conversion script in the docs build process.

What I did was take the original PNG, decrease the resolution, export it as JPG, then put it through JPG compression. I'll come up with a better solution for this

2022-05-19 12:13 UTC, mnmkng approved these changes

2022-05-19 12:13 UTC, merged