docs: replace most references to the Apify SDK with Crawlee
apify/apify-docs pull request #416
Opened 2022-07-29 10:47 UTC by mstephen19

In this PR, I'll be replacing references to the Apify SDK with Crawlee, as well as replacing code examples with their Crawlee counterparts.

**Note:** The Apify SDK will still need to be referenced in some lessons, as we use it to communicate with the platform and use the storage APIs.

2022-08-08 09:03 UTC, AndreyBykov commented
@mstephen19 just checking whether you're planning to work on it this week. If not - I would probably take it over, so let me know :)

2022-08-10 13:01 UTC, mstephen19 commented
Preview: https://developers.apify.com/academy/anti-scraping?version=sdk-crawlee-examples

2022-08-12 08:43 UTC, mstephen19 commented
This migration is potentially rough around the edges. Look through the [preview](https://developers.apify.com/academy/anti-scraping?version=sdk-crawlee-examples). If you find any issues or inconsistencies, definitely point it out.

2022-08-12 08:56 UTC, mnmkng commented
Not sure if related to the changes, probably not, but found this beauty 😄
![CleanShot 2022-08-12 at 10 49 53@2x](https://user-images.githubusercontent.com/23726914/184320728-3f43216e-4714-475a-b4e3-62034fa3f172.png)

2022-08-12 08:59 UTC, mstephen19 commented
> Not sure if related to the changes, probably not, but found this beauty 😄 ![CleanShot 2022-08-12 at 10 49 53@2x](https://user-images.githubusercontent.com/23726914/184320728-3f43216e-4714-475a-b4e3-62034fa3f172.png)

<img width="612" alt="Screen Shot 2022-08-12 at 10 59 00" src="https://user-images.githubusercontent.com/87805115/184321325-ec55a23d-5202-4d3a-a1e5-10648b1efb3c.png">

Looks like the same issue someone else was having too.

2022-08-12 10:01 UTC, mnmkng requested changes

2022-08-12 10:01 UTC, mnmkng commented on content/academy/web_scraping_for_beginners/crawling/dealing_with_dynamic_pages.md
```suggestion
    requestHandler: async ({ parseWithCheerio }) => {
        // Create the $ object based on the page's content
        const $ = parseWithCheerio();

```

2022-08-12 10:01 UTC, mnmkng commented on content/academy/web_scraping_for_beginners/crawling/dealing_with_dynamic_pages.md
>  import cheerio from 'cheerio';
```suggestion
```

2022-08-12 10:01 UTC, mnmkng commented on content/academy/web_scraping_for_beginners/crawling/dealing_with_dynamic_pages.md
please fix it elsewhere as well

2022-08-12 10:02 UTC, mnmkng commented
Thanks a lot Matt. Not the best job in the world, but needed to be done! Appreciate it.

2022-08-12 10:17 UTC, B4nan commented on content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
> +else await withAPI();
this hurts my eyes  😭 

```suggestion
if (useClient) {
    await withClient();
} else {
    await withAPI();
}
```

2022-08-12 10:40 UTC, B4nan commented on content/academy/expert_scraping_with_apify/saving_useful_stats.md
> +- Learn about the [`failedRequestHandler` function](https://crawlee.dev/api/browser-crawler/interface/BrowserCrawlerOptions#failedRequestHandler).
we should mention the newly added `errorHandler` too i guess, thats the one triggered on each failure, on each retry

https://crawlee.dev/api/browser-crawler/interface/BrowserCrawlerOptions#errorHandler

2022-08-12 14:57 UTC, metalwarrior665 requested changes

2022-08-12 14:57 UTC, metalwarrior665 commented on content/academy/anti_scraping/mitigation/using_proxies.md
> +    },
`label` is now a top-level property on Request

2022-08-12 14:57 UTC, metalwarrior665 commented on content/academy/expert_scraping_with_apify/solutions/actor_building.md
>                  label: labels.PRODUCT,
Let's make sure all labels are now top level property in all examples

2022-08-12 14:57 UTC, metalwarrior665 commented on content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
> +    url.search = new URLSearchParams({
The purpose is to try both client and raw API just to get hands on it

2022-08-12 15:18 UTC, mstephen19 commented on content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
> +    url.search = new URLSearchParams({
The purpose is to teach them how to use the Apify API via `Apify.call` or directly

2022-08-12 15:19 UTC, mstephen19 commented on content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
> +else await withAPI();
Why?

2022-08-15 16:54 UTC, mnmkng commented on content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
> +    url.search = new URLSearchParams({
Ok, let's not deal with this now, because it's not related to Crawlee migration 👍

2022-08-15 16:55 UTC, mnmkng approved these changes
I don't have time to rereview unfortunately, so I propose we merge this and deal with issues later as with bugs.

2022-08-16 07:19 UTC, merged