Update webhooks section
apify/apify-docs pull request #456
Opened 2022-10-10 12:29 UTC by m-murasovs

2022-10-14 16:05 UTC, valekjo requested changes

2022-10-14 16:05 UTC, valekjo commented on content/docs/integrations/slack.md
> +When an actor doesn’t require you to fill in any input fields, you can run it by simply typing `/apify run [actor name]`.
Wow, actually didn't know about this! Just it's `/apify call ...`

2022-10-14 16:05 UTC, valekjo commented on content/docs/integrations/slack.md
> +Then, head back to your actor to finish the setup. Select what type of events you would like to be notified of (e.g., when a run is created, when a run succeeds, when a run fails, etc.), your workspa
```suggestion
Then, head back to your task to finish the setup. Select what type of events you would like to be notified of (e.g., when a run is created, when a run succeeds, when a run fails, etc.), your workspace, and the channel you want to receive the notifications in (you can set up an ad-hoc channel for this test). In the **Message** field, you can see how the notification will look, or you can craft a new custom one.
```

2022-10-14 16:05 UTC, valekjo commented on content/docs/integrations/slack.md
> +## [](#step-one) Step 1: Create a task in Apify Console
I didn't get why the task is created first, but is it for the purpose of showing how to run it later directly from slack?

2022-10-17 09:27 UTC, m-murasovs commented on content/docs/integrations/webhooks/actions.md
> +<!-- If the URL points toward APify, we don't need to add the token because it gets added automatically -->
Yep 😄

2022-10-17 12:24 UTC, valekjo commented on content/docs/integrations/slack.md
> +## [](#step-one) Step 1: Create a task in Apify Console
Yep, I think that should be ok.

2022-10-18 12:24 UTC, valekjo approved these changes

2022-10-18 12:32 UTC, merged