feat: Reorganizing access rights
apify/apify-docs pull request #543
Opened 2023-03-10 10:10 UTC by mtrunkat

I slightly reorganized access rights sections as access rights should not be above the organization account - those are 2 different features, so now they are both under the "Collaboration":

![obrazek](https://user-images.githubusercontent.com/594801/224288770-3cbcea9e-0503-4211-9454-71e9be1aeecf.png)

2023-03-10 10:23 UTC, B4nan commented
I guess we should enable the PR checks for all branches, now they are used only for PRs targetting master (and I don't think we did that on purpose).

2023-03-10 13:27 UTC, mtrunkat commented
@B4nan let's do it. It's a good idea. I am sometimes creating these PR chains for an easier review

#532 ↩️ #542 ↩️ #543

2023-03-10 13:55 UTC, B4nan commented
Here you go: 

https://github.com/apify/apify-docs/commit/508d5f265f01bd13d7638c913cf16c7857105182

2023-03-16 15:30 UTC, PerVillalva approved these changes
Just capitalized a few instances of the word Actor to align with the new guidelines. Otherwise, everything seems to be fine.

2023-03-21 07:42 UTC, TheoVasilis requested changes

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/actors/running/runs_and_builds.md
> +You can share your actor runs with other Apify users via the [access rights](../../collaboration/index.md) system.
```suggestion
You can share your Actor runs with other Apify users via the [access rights](../../collaboration/index.md) system.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/actors/running/tasks.md
> +Like any other resource, you can share your actor tasks with other Apify users via the [access rights](../../collaboration/index.md) system.
```suggestion
Like any other resource, you can share your Actor tasks with other Apify users via the [access rights](../../collaboration/index.md) system.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/actors/running/tasks.md
> +Under the **Settings** tab of their detail page, you can grant [access rights](../../collaboration/index.md) to other Apify users.
```suggestion
You can grant [access rights](../../collaboration/index.md) to other Apify users under the **Settings** tab of their detail page.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/collaboration/access_rights.md
> +You can easily and securely share your own resources - Actors, tasks, key-value stores, datasets, and request queues with other users using a [granular](https://www.google.com/search?client=firefox-b
```suggestion
You can easily and securely share your own resources - Actors, tasks, key-value stores, datasets, and request queues - with other users by using a [granular](https://www.google.com/search?client=firefox-b-d&q=define+granular+permissions) permissions system. This enables you, for example, to let your colleague run an [Actor](../actors/index.md) or view a [dataset](../storage/dataset.md) but not modify it.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/collaboration/access_rights.md
> +[Storages](../storage/index.md) (key-value stores, request queues, and datasets) are sharable the same way with, for example, just **read** permission or a combination of both **read** and **write**
```suggestion
[Storages](../storage/index.md) (key-value stores, request queues, and datasets) are sharable in the same way as a **read** permission or a combination of both **read** and **write** permissions.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/collaboration/access_rights.md
> +To share an Actor, task, key-value store, request queue, or dataset, click on the **Actions** button in the top-right corner and select **Share**. You can add a collaborator using their **user ID**,
```suggestion
To share an Actor, task, key-value store, request queue, or dataset, click on the **Actions** button in the top-right corner and select **Share**. You can add a collaborator by using their **user ID**, **email**, or **username**. Once you have added the collaborator, you can configure their permissions.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/collaboration/index.md
> +        <td>Another way to share your Actor with other users is to publish it in <a href="https://apify.com/store">Apify Store</a>. When publishing your Actor, you can make it a Paid Actor and get pa
```suggestion
        <td>Another way to share your Actor with other users is to publish it in <a href="https://apify.com/store">Apify Store</a>. When publishing your Actor, you can make it a Paid Actor and get paid by the users benefiting from your tool. For more information, read the <a href="/platform/actors/publishing">publishing and monetization</a> section.</td>
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/collaboration/organization_account/index.md
>  The Free and Personal plans are [restricted to 9 seats](https://apify.com/pricing), while the Team plan comes with 9, which you can increase later. If you are on the Team plan and want to add some mo
```suggestion
The Free and Personal plans are [restricted to 9 seats](https://apify.com/pricing), while the Team plan comes with a minimum of 9, which you can increase later. If you are on the Team plan and want to add some more seats to the 9 it comes with, head over to your [Billing page and click on Subscriptions](https://console.apify.com/billing-new#/subscription). Click on **Upgrade**, and, in the **Add-ons** section, and add as many additional seats as you need. Then, just complete the upgrade process, and you're done.
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/schedules.md
> +You can invite other Apify users to view or modify your schedules using the [access rights](./collaboration/index.md) system. See the [full list of permissions](./collaboration/list_of_permissions.md
```suggestion
You can invite other Apify users to view or modify your schedules with the [access rights](./collaboration/index.md) system. See the [full list of permissions](./collaboration/list_of_permissions.md).
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/storage/dataset.md
> +You can invite other Apify users to view or modify your datasets using the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permissions.m
```suggestion
You can invite other Apify users to view or modify your datasets with the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permissions.md).
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/storage/index.md
> +You can invite other Apify users to view or modify your storages using the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permissions.m
```suggestion
You can invite other Apify users to view or modify your storages with the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permissions.md).
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/storage/key_value_store.md
> +You can invite other Apify users to view or modify your key-value stores using the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permi
```suggestion
You can invite other Apify users to view or modify your key-value stores with the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permissions.md).
```

2023-03-21 07:42 UTC, TheoVasilis commented on sources/platform/storage/request_queue.md
> +You can invite other Apify users to view or modify your request queues using the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permiss
```suggestion
You can invite other Apify users to view or modify your request queues with the [access rights](../collaboration/index.md) system. See the [full list of permissions](../collaboration/list_of_permissions.md).
```

2023-03-21 09:15 UTC, merged