feat: Restructuring and updating proxy section of platform docs
apify/apify-docs pull request #575
Opened 2023-04-13 07:21 UTC by jirimoravcik

2023-07-14 12:23 UTC, mtrunkat requested changes
I made a PR suggesting some changes plus describing 2 more changes I'd proceed before merging this

2023-07-21 08:22 UTC, TheoVasilis requested changes

2023-07-21 08:22 UTC, TheoVasilis commented on sources/platform/proxy/usage.md
> +            <p>If specified, to for example <code>session-new_job_123</code>, all proxied requests with the same session identifier are routed through the same IP address. If not specified, each prox
```suggestion
            <p>If specified to <code>session-new_job_123</code>, for example, all proxied requests with the same session identifier are routed through the same IP address. If not specified, each proxied request is assigned a randomly picked least used IP address.</p>
```

2023-07-21 09:10 UTC, TheoVasilis approved these changes

2023-07-21 09:43 UTC, mtrunkat approved these changes

2023-07-21 09:44 UTC, merged