feat(app): GitHub integration
apify/apify-docs pull request #576
Opened 2023-04-17 12:16 UTC by HonzaTuron

Adding simple walkthrough for new GitHub integration

2023-06-02 07:58 UTC, jbartadev requested changes
1. I think we should also add the other step with the list of repositories - we can use the Apify account for the screenshot and maybe display a couple of our repos to explain this better with all the options (public projects as `crawlee` or `got-scraping` and also some private repo)
<img width="1043" alt="Snímek obrazovky 2023-06-02 v 9 54 42" src="https://github.com/apify/apify-docs/assets/45016873/3c4e2e3f-66ed-4b20-b440-6861ceb78ce5">
2. it'd be nice to describe the options:

- Searching through repositories
- Adding different account
- Managing permissions

2023-06-05 11:16 UTC, jbartadev commented on sources/platform/integrations/github.md
> +Learn how to create an Actor from a GitHub repository. This is useful if you want to use the GitHub integration to automatically deploy your code to Apify.
```suggestion
Learn how to create an Actor from a GitHub repository. This is useful if you want to automatically deploy and build your code on push to your GitHub repository.
```

2023-06-06 09:01 UTC, TheoVasilis requested changes

2023-06-06 09:01 UTC, TheoVasilis commented on sources/platform/integrations/github.md
> +To link account, click on _Add GitHub account_ and follow instructions on github.com. Certain organization or user can be selected.
```suggestion
To link an account, click on _Add GitHub account_ and follow the instructions on github.com. Certain organizations or users can be selected.
```

2023-06-06 09:01 UTC, TheoVasilis commented on sources/platform/integrations/github.md
> +If required repository is missing, try to find it with _Search_.
```suggestion
If the required repository is missing, try finding it with _Search_.
```

2023-06-06 09:01 UTC, TheoVasilis commented on sources/platform/integrations/github.md
> +Actor is created immediately from selected repository.
```suggestion
An Actor is created immediately from the selected repository.
```

2023-06-06 10:04 UTC, TheoVasilis approved these changes

2023-07-03 08:35 UTC, jbartadev approved these changes

2023-07-03 08:36 UTC, jbartadev commented
@HonzaTuron let's merge this as the GH integration is already out!

2023-07-03 11:51 UTC, merged