chore: prepare for reusable workflows
apify/apify-docs pull request #590
Opened 2023-05-12 13:27 UTC by lukasmrtvy

2023-05-15 08:21 UTC, mtrunkat approved these changes
Nice

2023-05-15 11:42 UTC, fnesveda requested changes
Looks good, let's just use the GitHub token of the Apify Service Account rather than the one from this repo. It should have enough permissions for this.

2023-05-15 11:42 UTC, fnesveda commented on .github/workflows/deploy.yaml
> +            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```suggestion
            GITHUB_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
```

2023-05-15 11:42 UTC, fnesveda commented on .github/workflows/invalidate.yaml
> +            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```suggestion
            GITHUB_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
```

2023-05-23 07:47 UTC, fnesveda approved these changes

2023-05-23 07:55 UTC, merged