feat: improve pay per result docs
apify/apify-docs pull request #597
Opened 2023-05-24 15:38 UTC by mhamas

Adding information about where to find actor-level stats and how to set maximum number of items an Actor should return.

2023-05-25 09:39 UTC, TheoVasilis requested changes

2023-05-25 09:39 UTC, TheoVasilis commented on sources/platform/actors/running/store.md
> +You can set a limit on how many items an Actor should return and you will be charged for in Options on the Actor detail page, in the section below the input section.
```suggestion
You can set a limit on how many items an Actor should return and the amount you will be charged in Options on the Actor detail page in the section below the Actor input.
```

2023-05-25 09:39 UTC, TheoVasilis commented on sources/platform/actors/running/store.md
> +If you wish to see how much you have been charged for a particular actor, you will find this information
```suggestion
If you wish to see how much you have been charged for a particular Actor, you will find this information
```

2023-05-25 09:39 UTC, TheoVasilis commented on sources/platform/actors/running/store.md
> +on the bottom of the [Usage tab](https://console.apify.com/billing).
```suggestion
at the bottom of the [Usage tab](https://console.apify.com/billing).
```

2023-05-25 12:00 UTC, mhamas commented on sources/platform/actors/running/store.md
> +You can set a limit on how many items an Actor should return and you will be charged for in Options on the Actor detail page, in the section below the input section.
solved by Theo's change

2023-05-25 12:29 UTC, TheoVasilis approved these changes

2023-05-26 05:59 UTC, novotnyj approved these changes

2023-05-26 08:41 UTC, merged