feat: explain usage usd on run and build objects
apify/apify-docs pull request #677
Opened 2023-08-14 13:11 UTC by mhamas

Explaining that when you pass auth token to run/build GET requests, you get dollar values using the pricing effective at the time of query.

2023-08-14 14:16 UTC, TheoVasilis requested changes, later dismissed

2023-08-14 14:16 UTC, TheoVasilis commented on sources/platform/api_v2/api_v2_reference.apib
> +This endpoint does not require the authentication token, the calls are authenticated using a hard-to-guess ID of the build. If
```suggestion
This endpoint does not require the authentication token. The calls are authenticated using a hard-to-guess ID of the build. If
```

2023-08-14 14:16 UTC, TheoVasilis commented on sources/platform/api_v2/api_v2_reference.apib
> +This endpoint does not require the authentication token, the calls are authenticated using a hard-to-guess ID of the run. If
```suggestion
This endpoint does not require the authentication token. The calls are authenticated using a hard-to-guess ID of the run. If
```

2023-08-15 09:35 UTC, drobnikj requested changes
The usageUsd and usageUsdTotal is presented in list of runs or builds. Plus in some endpoints which we can run just with token, we should add info there as well. 

You can write short info (or reuse current one) into https://docs.apify.com/platform/actors/running/usage-and-resources
and link it into API reference and in the console.

2023-08-16 11:08 UTC, drobnikj approved these changes

2023-08-16 12:54 UTC, TheoVasilis requested changes, later dismissed

2023-08-16 12:54 UTC, TheoVasilis commented on sources/platform/actors/running/usage_and_resources.md
> +Note that for technical reasons, every time you see the usage in dollars on a specific historical Actor run or build in the API or the Apify Console, your current service pricing is used to compute t
```suggestion
Note that for technical reasons, every time you see the usage in dollars on a specific historical Actor run or build in the API or Apify Console, your current service pricing is used to compute the dollar amount,
```

2023-08-22 08:28 UTC, merged