docs: Added multiselect to input schema specification
apify/apify-docs pull request #713
Opened 2023-09-22 15:16 UTC by gippy

Resolves: https://github.com/apify/apify-docs/issues/704

![image](https://github.com/apify/apify-docs/assets/3171028/0b96aa25-e1c0-4fcb-8dc8-014894c53adc)

2023-09-23 08:02 UTC, TheoVasilis requested changes

2023-09-23 08:02 UTC, TheoVasilis commented on sources/platform/actors/development/actor_definition/input_schema/specification.md
> +Editor type `select` gives the user option to pick items from a select allowing multiple choices. Please check this example of how to define the multiselect field
```suggestion
Editor type `select` allows the user to pick items from a select, providing multiple choices. Please check this example of how to define the multiselect field:
```

2023-09-23 08:02 UTC, TheoVasilis commented on sources/platform/actors/development/actor_definition/input_schema/specification.md
> +To correctly define options for multiselect, you need to define the `items` property and then provide values and optionally labels in `enum` and `enumTitles` properties.
```suggestion
To correctly define options for multiselect, you need to define the `items` property and then provide values and (optionally) labels in `enum` and `enumTitles` properties.
```

2023-09-25 07:13 UTC, m-murasovs approved these changes

2023-09-25 07:58 UTC, merged