feat: Add docs for run/build DELETE endpoint
apify/apify-docs pull request #727
Opened 2023-10-05 08:52 UTC by Jkuzz

resolves https://github.com/apify/apify-core/issues/12561
changes made by https://github.com/apify/apify-core/pull/12531, https://github.com/apify/apify-core/pull/12504

2023-10-05 10:22 UTC, TheoVasilis requested changes

2023-10-05 10:22 UTC, TheoVasilis commented on sources/platform/api_v2/api_v2_reference.apib
> +Delete the run. Only finished builds can be deleted. Only the person or organisation that initiated the run can delete it.
```suggestion
Delete the run. Only finished builds can be deleted. Only the person or organization that initiated the run can delete it.
```

2023-10-05 13:19 UTC, TheoVasilis approved these changes

2023-10-09 11:38 UTC, drobnikj requested changes

2023-10-10 09:06 UTC, drobnikj approved these changes

2023-10-10 09:10 UTC, merged