docs(api): update reference for log endpoints, including the new build ones
apify/apify-docs pull request #852
Opened 2024-02-09 14:48 UTC by tobice

There are two new endpoints, `/actor-builds/<BUILD_ID>/log` and `/acts/<ACTOR_ID>/builds/<BUILD_ID>/log`. This PR adds the corresponding reference.

The endpoints behave the same (modulo authentication) as `/logs/<BUILD_OR_RUN_ID` but due to the limitations of API Blueprint, I couldn't find an easy way to share the reference. Using the same approach as for `/actor-runs/{RUN_ID}/log`, basically just an inline link, also didn't work, as without proper request/response definition, the headlines would not render at all 🤷 Hence a bit of copy-paste seemed like the best approach.

This PR also:

* Removes some outdated information about how the logs endpoint work (they return a standard 200, no redirects)
* Fixes the reference for `/actor-runs/{RUN_ID}/log`

2024-02-09 14:51 UTC, tobice commented
The actual API should probably be merged and released first. https://github.com/apify/apify-core/pull/14281

2024-02-12 10:47 UTC, drobnikj requested changes
Just a few notes, I think we can remove `/v2/acts/{actorId}/builds/{buildId}/log`
as the `/v2/acts/{actorId}/builds/{buildId}` was deprecated in favor of `v2/actor-builds/{buildId}`.

2024-02-12 10:47 UTC, drobnikj commented on sources/platform/api_v2/api_v2_reference.apib
> +2017-07-14T06:00:49.733Z Application started.
It looks that your changes reporting some semantic issues
![image](https://github.com/apify/apify-docs/assets/11837643/39ff9e81-7480-402e-b00b-0f040c49ff16)

2024-02-12 10:47 UTC, drobnikj commented on sources/platform/api_v2/api_v2_reference.apib
> +## Build logs [/v2/acts/{actorId}/builds/{buildId}/log{?token,stream,download}]
```suggestion
## Build log [/v2/acts/{actorId}/builds/{buildId}/log{?token,stream,download}]
```

As the build has one log, it is not a collection of logs.

2024-02-12 10:47 UTC, drobnikj commented on sources/platform/api_v2/api_v2_reference.apib
> +## Build logs [/v2/actor-builds/{buildId}/log{?token,stream,download}]
```suggestion
## Build log [/v2/actor-builds/{buildId}/log{?token,stream,download}]
```

2024-02-12 10:49 UTC, drobnikj commented
@tobice As we discussed, you can check apiary validation in Apiary UI check here https://github.com/apify/apify-docs/blob/master/CONTRIBUTING.md#pre-release-testing

2024-02-13 08:42 UTC, fnesveda approved these changes
Cool 👍

2024-02-13 08:57 UTC, drobnikj approved these changes
👍

2024-02-13 09:10 UTC, tobice commented
Thanks for review ❤️ Will merge once the API is released.

2024-02-13 13:47 UTC, merged