feat(request-queue): Extend rq documentation with rqv2 features
apify/apify-docs pull request #904
Opened 2024-03-27 16:30 UTC by drobnikj

2024-03-28 12:55 UTC, drobnikj commented
I got lots of warnings from Lychee. I don't care if you want to do changes directly into my code. Maybe it is better than commenting. @TC-MO

2024-03-28 13:21 UTC, TC-MO commented
I see 1 error in lychee 404, but from what I understand it is because you are already linking to the tutorial that you will create at later point?

2024-04-02 09:21 UTC, drobnikj commented
> the tutorial that you will create at later point?

Yep, I would create a tutorial in a separate PR.

2024-04-03 09:16 UTC, mtrunkat requested changes

2024-04-03 09:16 UTC, mtrunkat commented on sources/platform/storage/request_queue.md
> +Our design facilitates the simultaneous processing of requests by multiple Actor runs or server instances, perfectly suiting large-scale web crawling projects.
```suggestion
Our design facilitates the simultaneous processing of requests by multiple clients (for example,  Actor runs) or server instances, perfectly suiting large-scale web crawling projects.
```

2024-04-03 09:16 UTC, mtrunkat commented on sources/platform/storage/request_queue.md
> +
I'd also mention that lock TTL should be set to the timeout used for request processing. Also, mention a page function timeout, or what it's called in Crawlee, as an example.

2024-04-03 09:16 UTC, mtrunkat commented on sources/platform/storage/request_queue.md
> +
This

> Request queues in Apify power complex web crawling and data scraping operations with a set of robust features.
These features boost your projects' flexibility, efficiency, and scalability.

sounds like a marketing bull-💩 and a bit like GPT. Let's keep the docs accurate and technical with something more like:

> Request queue as a storage type was built with scraping in mind to enable developers to write scraping logic in an efficient and scalable way. The Apify tooling, including Crawlee and Apify SDKs, incorporates all these features, enabling users to leverage them effortlessly without extra configuration.
> 
> In the following section, we will discuss each of the main features in depth.

2024-04-04 09:03 UTC, TC-MO commented on sources/platform/storage/request_queue.md
> +The Apify tooling, including [Crawlee](https://crawlee.dev/) and [Apify SDKs](https://docs.apify.com/sdk/js/), incorporates all these features, enabling users to leverage them effortlessly without ex
Is this feature available in Python SDK as well? If so I would add separate link something like:
```suggestion
The Apify tooling, including [Crawlee](https://crawlee.dev/), [Apify JS SDK](https://docs.apify.com/sdk/js/), and [Apify Python SDK](https://docs.apify.com/sdk/python/) , incorporates all these features, enabling users to leverage them effortlessly without extra configuration.
```

Once we have a unified landing page for SDKs we can change it for a singular link.

2024-04-04 09:04 UTC, TC-MO commented on sources/platform/storage/request_queue.md
> +### Persistence and retention {#persistence-and-retention}
```suggestion
### Persistence and retention
```

If there is no difference between heading and anchor in curly brackets we can omit it. and Docusaurus will generate anchor based on the heading

2024-04-04 09:31 UTC, TC-MO approved these changes

2024-04-09 07:22 UTC, mtrunkat approved these changes
Just Franta's point + TODOs

2024-04-10 13:28 UTC, fnesveda approved these changes

2024-04-10 14:31 UTC, merged