feat: Added tutorial to scraper website from multiple Actor runs
apify/apify-docs pull request #918
Opened 2024-04-10 15:37 UTC by drobnikj

2024-04-17 12:07 UTC, fnesveda requested changes
Looks good, I just had some suggestions about naming and structure.

I would just rename "Master" to "orchestrator" to make it more intuitive, and change the folder structure of the examples to this:
```
- examples/
    - parallel-scraping/
        - orchestrator/
            - .actor/
            - src/
            - ...
        - scraper/
            - .actor/
            - src/
            - ...
```

2024-04-17 12:07 UTC, fnesveda commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +title: Scrape website from multiple Actor runs
Let's rename this file to `parallel-scraping.md`
```suggestion
title: Scrape website in parallel with multiple Actor runs
```

2024-04-17 12:09 UTC, fnesveda commented
@metalwarrior665 Could you or someone from the delivery team who has more experience writing Actors than us review this, if it's OK from your point of view?

2024-04-17 12:29 UTC, drobnikj commented
> "Master" to "orchestrator"

I was afraid some renaming would happen, and I will need it to replace everywhere 😅

2024-04-17 14:11 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +> In a rush? You can check [full code example](https://github.com/apify/apify-docs/tree/master/examples/ts-parallel-runs-scraping-master) right away.
```suggestion
:::note In a rush? 

You can check [full code example](https://github.com/apify/apify-docs/tree/master/examples/ts-parallel-runs-scraping-master) right away.

:::
```

I would suggest refraining from using codeblock this way, admonitions are much more elegant solution for this kind of notes.

2024-04-17 14:14 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +> If you don't have Apify CLI installed, you can find the installation instructions [here](https://docs.apify.com/cli).
```suggestion
If you don't have Apify CLI installed, you can find the installation instructions [here](https://docs.apify.com/cli).
```

2024-04-17 14:23 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +<TabItem value="main.ts" label="main.ts">
nitpick, could we make sure that codetabs are in the same order throughout the whole doc? It's both for consistency sake and due to the fact that docusaurus changes tab in whole documents if it has the same value

2024-04-17 14:25 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +> If you are pushing the Actor for the first time, you will need to [login to your Apify account](https://docs.apify.com/cli/docs/reference#apify-login).
```suggestion
:::tip First login

If you are pushing the Actor for the first time, you will need to [login to your Apify account](https://docs.apify.com/cli/docs/reference#apify-login).

:::
```

2024-04-17 14:27 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +> You can check [full code example](https://github.com/apify/apify-docs/tree/master/examples/ts-parallel-runs-scraping-scraper).
```suggestion
You can check [full code example](https://github.com/apify/apify-docs/tree/master/examples/ts-parallel-runs-scraping-scraper).
```

2024-04-17 20:03 UTC, metalwarrior665 requested changes
I could imagine a solution without a master actor where the first run of the scraper would do the mastering as well and call itself with `childRun: true` and pass its queue/dataset. I think we used that approach sometime. But I haven't thought enough if it is really better UX-wise than a separate master.

2024-04-18 12:23 UTC, drobnikj commented
> imagine a solution without a master actor

Agree, but this one serves better as an example. It is more readable.

2024-04-18 12:31 UTC, drobnikj commented
> let's think if we could possibly later manage this on the SDK/platform side to make every actor using queue/dataset infinitely horizontally scalable

It can be some product feature. We can bundle it into SDK in some generic way and make some tweeks in the console UI to support this. 
cc product @zenisjan - the feature can be named "Better support for horizontal scaling of Actors"

2024-04-18 12:34 UTC, drobnikj commented on .eslintrc.json
> +    "ignorePatterns": ["examples/"]
The repository had no monorepo setup, so it created some issues. 
The actors itself has lint npm scripts, so the users can easily copy&paste source code and start using it even with linters.

2024-04-18 12:47 UTC, drobnikj commented on examples/ts-parallel-runs-scraping-scraper/src/main.ts
> +});
I would keep this logic on crawlee. I think it is fine that the scraper finishes once the queue is empty for a while. The locked requests will be handled by the run, which locks them.

2024-04-18 14:03 UTC, metalwarrior665 approved these changes

2024-04-19 08:38 UTC, mtrunkat reviewed
just one suggestion on naming in the main article, perhaps there are more places to alligned

2024-04-19 08:38 UTC, mtrunkat commented on sources/platform/storage/request_queue.md
> +A detailed tutorial on how to crawl one request queue from multiple Actor runs can be found in [Academy tutorials](https://docs.apify.com/academy/node-js/multiple-runs-scrape).
```suggestion
A detailed tutorial on how to process one request queue with multiple concurrent Actor runs can be found in [Academy tutorials](https://docs.apify.com/academy/node-js/multiple-runs-scrape).
```

IMHO you are not scraping the queue, you are scraping the website and have runs processing the queue.

2024-04-19 11:44 UTC, TC-MO approved these changes

2024-04-19 11:44 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +# Scraping website from multiple Actor runs
Is this different from `title` on purpose?

2024-04-19 11:44 UTC, TC-MO commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +<TabItem value="main.ts" label="main.ts">
can we switch the order of code tabs here for consistency?

2024-04-22 05:11 UTC, fnesveda approved these changes
Looks good, just two link fixes, plus I agree with the others' suggestions.

2024-04-22 05:11 UTC, fnesveda commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +You can check [full code example](https://github.com/apify/apify-docs/tree/master/examples/ts-parallel-scraping/orchestrator) right away.
Here a link to the whole folder with both Actors is better.
```suggestion
You can check [full code example](https://github.com/apify/apify-docs/tree/master/examples/ts-parallel-scraping) right away.
```

2024-04-22 05:11 UTC, fnesveda commented on sources/academy/tutorials/node_js/multiple-runs-scrape.md
> +If you don't have Apify CLI installed, check out our installation [instructions](https://docs.apify.com/cli).
```suggestion
If you don't have Apify CLI installed, check out our installation [instructions](https://docs.apify.com/cli/docs/installation).
```

2024-04-23 13:28 UTC, TC-MO commented
Is anything halting release of this tutorial?

2024-04-24 09:46 UTC, merged