feat: improve monetization docs
apify/apify-docs pull request #990
Opened 2024-05-01 15:43 UTC by mhamas

Small tweaks in Payouts and QA docs

2024-05-02 07:07 UTC, Jkuzz approved these changes

2024-05-10 08:26 UTC, TC-MO requested changes

2024-05-10 08:26 UTC, TC-MO commented on sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
> +If you make your Actor pay-per-result instead, you will set the price per 1,000 results, and users will be charged for your Actor solely based on the number of results your Actor produces. That's you
```suggestion
If you make your Actor pay-per-result instead, you will set the price per 1,000 results, and users will be charged for your Actor solely based on the number of results your Actor produces. That's your _revenue_. The underlying [platform usage](https://docs.apify.com/platform/actors/running/usage-and-resources) the Actor generates, using the free plan unit pricing, is your _cost_. Your profit which is then paid to you is computed as 80% of the revenue minus the costs, i.e. `(0.8 * revenue) - costs = profit`. This profit is also paid out monthly.
```

2024-05-10 08:26 UTC, TC-MO commented on sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
> +If you make your Actor pay-per-result instead, you will set the price per 1,000 results, and users will be charged for your Actor solely based on the number of results your Actor produces. That's you
as per style guide bold in prose should be used only to highlight UI elements

2024-05-10 08:26 UTC, TC-MO commented on sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
> +Payout invoices are created automatically on 14th of the new month. You will be notified and can access the new payout invoice, and any historical invoices, in the [**Settings > Payouts**](https://co
```suggestion
Payout invoices are created automatically on 14th of each month. You will be notified and can access the new payout invoice, and any historical invoices, in the [**Settings > Payouts**](https://console.apify.com/account/payouts) section in Apify Console. Once the new invoice is ready, you will need to review and approve it within a week in order for the payment to be processed. Note that if you do not approve the invoice, or let us know of any discrepancies, by the 20th of the month, the invoice will be auto-approved by the system on the 21st. If you have multiple Actors, the total profit is the sum of individual profits, and any losses and gains cancel out.
```

I think this makes it a little bit less ambiguous

2024-05-13 17:38 UTC, mhamas commented
@TC-MO applied suggestions, can you please re-review?

2024-05-13 18:01 UTC, TC-MO approved these changes

2024-05-14 07:34 UTC, mhamas commented
@TC-MO can you please check the lint errors? They seem unrelated, but can you confirm I can merge this? Thx

2024-05-14 08:14 UTC, TC-MO commented
They are unrelated to the changes but are found in the file that has been changed. In these cases I'd prefer not to leave any mdlint issues living in docs. This should take care of them.

2024-05-14 11:29 UTC, merged

2024-05-20 09:06 UTC, honzajavorek commented on sources/platform/actors/publishing/testing.mdx
> +If that's the case with your Actor, please contact support at [support@apify.com](mailto:support@apify.com) and explain your specific use case that justifies why the Actor should be excluded from the
@TC-MO Docusaurus seems to turn email addresses to links automatically. I just tried it locally and it works.

<img width="252" alt="Screenshot 2024-05-20 at 11 05 26" src="https://github.com/apify/apify-docs/assets/283441/e3765788-45ca-4fe7-aec1-9b29a089726f">

<img width="265" alt="Screenshot 2024-05-20 at 11 05 51" src="https://github.com/apify/apify-docs/assets/283441/889b42c4-953f-42c1-ad07-74801b0664d8">