docs: Add API Clients landing page
apify/apify-docs pull request #991
Opened 2024-05-02 13:18 UTC by HonzaTuron

Closes apify/apify-web#3622

Adds landing page for API clients (Python and JS). Menu item not added yet

**Differences design-wise:**
- Wasn't able to figure out background svg in hero section 
- In that case, not sure if that transparent section border makes sense

2024-05-05 10:39 UTC, jbartadev reviewed
Looks good! A couple of notes.

Please bump the ui-library before merging as the current version has broken code highlighting In code block for dark mode

In the case of the gradient background - it's up to @hanatsai if she is fine with that. There is a way how to do it for sure

2024-05-05 10:39 UTC, jbartadev commented on src/pages/api/index.tsx
> +                It connects you with any Actors and their tasks either in the Store or your own.</>}
The copy doesn't make sense here, I know it's in the design but we need to change it to something connected to API in general.

I'd probably do something short and simple like:

Apify API provides programmatic access to the [Apify platform](https://docs.apify.com/).

What do you think?

2024-05-05 10:39 UTC, jbartadev commented on src/pages/api/index.tsx
> +                                            <ActionLink to='https://docs.apify.com/api/client/js'>JavaScript client reference</ActionLink>
Let's remove the external icons from those

<img width="987" alt="Snímek obrazovky 2024-05-05 v 12 26 55" src="https://github.com/apify/apify-docs/assets/45016873/3cbe37b3-b7a9-4248-9aa0-9ba9b402d658">

2024-05-05 10:39 UTC, jbartadev commented on src/pages/api/index.tsx
> +                                        <GitHubButton href="https://github.com/apify/apify-client-js" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-c
Seems like the GH button is not picking up the right background in light mode, works on the homepage


<img width="831" alt="Snímek obrazovky 2024-05-05 v 12 28 37" src="https://github.com/apify/apify-docs/assets/45016873/e696599e-e89d-48a8-8ed0-e491613b2834">

2024-05-05 10:39 UTC, jbartadev commented on src/pages/api/index.tsx
> +                    The Apify API is built around REST.
Missing the links here - to REST

2024-05-05 10:39 UTC, jbartadev commented on src/pages/api/index.tsx
> +                            <BlogArticle
Wouldn't be better to define the IDs of the blog post and fetch them dynamically so the title and URL change if the blog post changes?

2024-05-05 10:39 UTC, jbartadev commented on src/pages/api/index.tsx
> +                    <RelatedArticlesWrapper>
There should be 2 columns on the tablet based on the design

<img width="953" alt="Snímek obrazovky 2024-05-05 v 12 35 41" src="https://github.com/apify/apify-docs/assets/45016873/20f4e832-cfd1-4112-82a0-09eadfe0ee67">

2024-05-06 11:26 UTC, jbartadev commented on src/pages/api/index.tsx
> +                            <BlogArticle
Yeah, fair. Let's not complicate it

2024-05-06 14:53 UTC, hanatsai commented
> Looks good! A couple of notes.
> 
> Please bump the ui-library before merging as the current version has broken code highlighting In code block for dark mode
> 
> In the case of the gradient background - it's up to @hanatsai if she is fine with that. There is a way how to do it for sure

I think it's fine, we can leave it as it is right now. :)

2024-05-06 15:12 UTC, hanatsai commented
My fault 😭 the get started button should be green 😭😭😭 Sorry!! 
<img width="600" alt="Screenshot 2024-05-06 at 17 12 03" src="https://github.com/apify/apify-docs/assets/102979339/5174616a-939d-4308-855a-399baf5e2a3e">

2024-05-06 15:21 UTC, HonzaTuron commented on nginx.conf
> -  rewrite ^/api/?$ /api/v2 redirect;
This is how we agreed with @B4nan how to redirect - we can rewrite original /v2. Also we want to redirect frome /api/client

2024-05-06 15:48 UTC, HonzaTuron commented
@hanatsai Observations adressed.

2024-05-07 09:56 UTC, hanatsai approved these changes

2024-05-07 11:20 UTC, jbartadev commented on src/pages/api/index.tsx
> +                    <RelatedArticlesWrapper>
@HonzaTuron now it's 3 columns on the tablet (should be 2)

<img width="1163" alt="Snímek obrazovky 2024-05-07 v 13 20 29" src="https://github.com/apify/apify-docs/assets/45016873/af9630f4-05d8-46d6-9588-eae75538a510">

2024-05-07 11:23 UTC, jbartadev approved these changes
Preapproving, details to solve

2024-05-07 11:23 UTC, jbartadev commented on src/pages/api/index.tsx
> +
Let's remove the empty lines from the code examples (between the comment and code)

2024-05-07 11:23 UTC, jbartadev commented on src/pages/api/index.tsx
> +
Also here, extra empty line between the comment and the other line of code

2024-05-07 11:27 UTC, baldasseva requested changes
Missing link in the navbar
<img width="933" alt="image" src="https://github.com/apify/apify-docs/assets/37815707/ce324347-161f-4823-8284-3499ec92e9ed">

2024-05-07 11:59 UTC, baldasseva approved these changes
all good now from my side

2024-05-07 11:59 UTC, merged

2024-05-07 12:11 UTC, B4nan commented on nginx.conf
> +  rewrite ^/api/client?$ /api redirect;
i think should be `/?`, meaning we redirect on `/api/client` and `/api/client/` but not `/api/client/xxx`. the way you have it means the `t` is optional, so its `/api/client` or `/api/clien`